### ISSUE TITLE
Can not update packwiz installer

### ISSUE THREAD

**Issue by Crafterluck** [comp500/packwiz-installer-bootstrap#12]
This error show up when starting an instanz. 

![Bildschirmfoto vom 2023-10-03 00-59-29](https://github.com/packwiz/packwiz-installer-bootstrap/assets/84713188/dd6564da-0e22-4826-917d-019dfabd9496)

**Comment by Crafterluck** [comment]
This was because of an rate limit.

**Comment by comp500** [comment]
Duplicate of #3
